config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/campaigns', to: 'campaigns#show_campaigns'
  get '/campaign_redirect/:value', to: 'campaigns#redirect', as: 'campaign_redirect'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :place_votes
end

app/models/place_vote.rb
class PlaceVote < ApplicationRecord
  belongs_to :campaign
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def show_campaigns
    campaigns = Campaign.all
    @attribute_names = campaigns.map(&:name)
    render 'campaigns'
  end
  def redirect
    @placed_votes = Campaign.find_by_name(params[:value]).place_votes
    render 'campaigns/place_votes' # Render the desired HTML view template
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/campaigns.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Campaigns</title>
</head>
<body>
<h1>Campaigns</h1>
<ul>
  <% @attribute_names.each do |value| %>
    <li><%= button_to value, campaign_redirect_path(value), method: :get %></li>
  <% end %>
</ul>
</body>
</html>

app/views/campaigns/place_votes.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Another HTML File</title>
</head>
<body>
<h1>List of Objects</h1>
<table>
  <thead>
  <tr>
    <th>Campaign Name</th>
    <th>Validity</th>
    <th>Choice</th>
    <th>Time of Vote</th>
  </tr>
  </thead>
  <tbody>
  <% @placed_votes.each do |object| %>
    <tr>
      <td><%= object.campaign.name %></td>
      <td><%= object.validity %></td>
      <td><%= object.choice %></td>
      <td><%= Time.at(object.time_of_vote).strftime("%Y-%m-%d %H:%M:%S") %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VladTestingStuff</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>